cpio: added REGLinux configuration

diff --git a/fs/cpio/init b/fs/cpio/init
--- a/fs/cpio/init
+++ b/fs/cpio/init
@@ -1,15 +1,237 @@
 #!/bin/sh
-# devtmpfs does not get automounted for initramfs
-/bin/mount -t devtmpfs devtmpfs /dev
+# REGLinux configuration
 
-# use the /dev/console device node from devtmpfs if possible to not
-# confuse glibc's ttyname_r().
-# This may fail (E.G. booted with console=), and errors from exec will
-# terminate the shell, so use a subshell for the test
-if (exec 0</dev/console) 2>/dev/null; then
-    exec 0</dev/console
-    exec 1>/dev/console
-    exec 2>/dev/console
+# update the rescue if needed
+do_update_rescue() {
+    if test -e /boot_root/boot/rescue.update
+    then
+        mount -o remount,rw /boot_root || return 1
+        mv /boot_root/boot/rescue.update /boot_root/boot/rescue || return 1
+        # remove the overlay when updating
+        if test -e /boot_root/boot/overlay
+        then
+            mv /boot_root/boot/overlay /boot_root/boot/overlay.old  || return 1
+        fi
+        mount -o remount,ro /boot_root || return 1
+    fi
+}
+
+# update the modules if needed
+do_update_modules() {
+    if test -e /boot_root/boot/modules.update
+    then
+        mount -o remount,rw /boot_root || return 1
+        if test -e /boot_root/boot/modules
+        then
+            rm /boot_root/boot/modules || return 1
+        fi
+        mv /boot_root/boot/modules.update /boot_root/boot/modules || return 1
+        # remove the overlay when updating
+        if test -e /boot_root/boot/overlay
+        then
+            mv /boot_root/boot/overlay /boot_root/boot/overlay.old  || return 1
+        fi
+        mount -o remount,ro /boot_root || return 1
+    fi
+}
+
+# update the firmware if needed
+do_update_firmware() {
+    if test -e /boot_root/boot/firmware.update
+    then
+        mount -o remount,rw /boot_root || return 1
+        if test -e /boot_root/boot/firmware
+        then
+            rm /boot_root/boot/firmware || return 1
+        fi
+        mv /boot_root/boot/firmware.update /boot_root/boot/firmware || return 1
+        # remove the overlay when updating
+        if test -e /boot_root/boot/overlay
+        then
+            mv /boot_root/boot/overlay /boot_root/boot/overlay.old  || return 1
+        fi
+        mount -o remount,ro /boot_root || return 1
+    fi
+}
+
+# update the rootfs if needed
+do_update_rootfs() {
+    if test -e /boot_root/boot/reglinux.update
+    then
+        mount -o remount,rw /boot_root || return 1
+        mv /boot_root/boot/reglinux.update /boot_root/boot/reglinux || return 1
+        # remove the overlay when updating
+        if test -e /boot_root/boot/overlay
+        then
+            mv /boot_root/boot/overlay /boot_root/boot/overlay.old  || return 1
+        fi
+        mount -o remount,ro /boot_root || return 1
+    fi
+}
+
+# mount the modules
+do_mount_modules() {
+    mkdir -p /new_root/lib/modules
+    mount /boot_root/boot/modules /new_root/lib/modules || return 1
+}
+
+# mount the firmware
+do_mount_firmware() {
+    mkdir -p /new_root/lib/firmware
+    mount /boot_root/boot/firmware /new_root/lib/firmware || return 1
+}
+
+do_mount() {
+    if mount -o ro "${1}"           /boot_root;
+    then
+        return 0;
+    fi
+    return 1
+}
+
+do_rescue() {
+    # mount the rootfs
+    mount /boot_root/boot/rescue /overlay_root/base || return 1
+
+    # mount the future root in read write
+    if ! mount -t overlay overlay -o rw,lowerdir=/overlay_root/base,upperdir=/overlay_root/overlay,workdir=/overlay_root/work /new_root
+    then
+	# mount only as squashfs, no overlay (xu4 doesn't support overlayfs)
+	    mount /boot_root/boot/rescue /new_root || return 1
+    fi
+
+    do_mount_firmware
+    do_mount_modules
+
+    # moving current mounts
+    mount --move /boot_root    /new_root/boot     || return 1
+    mount --move /overlay_root /new_root/overlay  || return 1
+    mount --move /sys  	       /new_root/sys  	  || return 1
+    mount --move /proc 	       /new_root/proc 	  || return 1
+    mount --move /dev  	       /new_root/dev  	  || return 1
+
+    # Switch to rescue filesystem
+    exec switch_root /new_root /sbin/init || return 1
+
+    return 0
+}
+
+do_update() {
+    do_rescue || return 1
+}
+
+do_plymouth() {
+    export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/lib/plymouth
+
+    # Plymouth needs /dev/pts mounted
+    mkdir /dev/pts
+    mount -t devpts /dev/pts /dev/pts
+
+    /usr/sbin/plymouthd --graphical-boot --attach-to-session --mode=boot
+    /usr/bin/plymouth --show-splash
+}
+
+do_root() {
+    mkdir -p /boot_root /new_root /overlay_root /sys /proc || return 1
+    mount -t proc  -o nodev,noexec,nosuid proc  /proc  	|| return 1
+    mount -t sysfs -o nodev,noexec,nosuid sysfs /sys 	|| return 1
+
+    # read the parameters
+    read -r cmdline < /proc/cmdline
+    for param in ${cmdline} ; do
+        case ${param} in
+            dev=*)   dev=${param#dev=};;
+            label=*) label=${param#label=};;
+        esac
+    done
+
+    # look for devices
+    mount -t devtmpfs none /dev
+
+    # Start plymouth
+    #do_plymouth
+
+    MOUNTARG=none
+    test -n "${dev}"   && MOUNTARG=${dev}
+    test -n "${label}" && MOUNTARG=LABEL=${label}
+
+    while ! do_mount "${MOUNTARG}"
+    do
+        echo "Waiting for the root device"
+        sleep 1
+    done
+
+    # Process updates if any
+    do_update_rescue
+    do_update_modules
+    do_update_firmware
+    do_update_rootfs
+
+    # create an overlay on memory
+    mount -t tmpfs -o size=32M tmpfs /overlay_root || return 1
+    mkdir /overlay_root/base /overlay_root/overlay /overlay_root/work /overlay_root/saved || return 1
+
+    # fill the overlay with the stored one
+    if test -f /boot_root/boot/overlay
+    then
+        # the mount can fail if the fs was open in write and not correctly closed
+        if mount -o ro /boot_root/boot/overlay /overlay_root/saved
+        then
+            cp -pr /overlay_root/saved/* /overlay_root/overlay || return 1
+            umount /overlay_root/saved                         || return 1
+        fi
+    fi
+
+    # First test for RESCUE mode
+    if test -f /boot_root/REG_RESCUE
+    then
+        mount -o remount,rw /boot_root || return 1
+        rm -f /boot_root/REG_RESCUE
+        mount -o remount,ro /boot_root || return 1
+        do_rescue || return 1
+        sync
+        reboot
+        return 0
+    fi
+
+    # Then test for UPDATE mode
+    if test -f /boot_root/REG_UPDATE
+    then
+        mount -o remount,rw /boot_root || return 1
+        rm -f /boot_root/REG_UPDATE
+        mount -o remount,ro /boot_root || return 1
+        do_update || return 1
+        sync
+        reboot
+        return 0
+    fi
+
+    # mount the rootfs
+    mount /boot_root/boot/reglinux /overlay_root/base || return 1
+
+    # mount the future root in read write
+    if ! mount -t overlay overlay -o rw,lowerdir=/overlay_root/base,upperdir=/overlay_root/overlay,workdir=/overlay_root/work /new_root
+    then
+        # mount only as squashfs, no overlay (xu4 doesn't support overlayfs)
+        mount /boot_root/boot/reglinux /new_root || return 1
+    fi
+
+    do_mount_firmware
+    do_mount_modules
+
+    # moving current mounts
+    mount --move /boot_root    /new_root/boot     || return 1
+    mount --move /overlay_root /new_root/overlay  || return 1
+    mount --move /sys  	       /new_root/sys  	  || return 1
+    mount --move /proc 	       /new_root/proc 	  || return 1
+    mount --move /dev  	       /new_root/dev  	  || return 1
+
+    # switch to the new root
+    exec switch_root /new_root /sbin/init || return 1
+}
+
+if ! do_root
+then
+    echo "Cannot boot to mounted filesystem !"
+    /bin/bash
 fi
-
-exec /sbin/init "$@"
